# Generated by Django 4.1.3 on 2022-12-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='overall_comment',
            field=models.CharField(blank=True, default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='students',
            name='pre_training_comment',
            field=models.CharField(blank=True, default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='students',
            name='training_day_arrival',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='students',
            name='training_day_attendance',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='students',
            name='training_day_comment',
            field=models.CharField(blank=True, default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='students',
            name='training_day_left',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
