# Generated by Django 4.1.3 on 2022-12-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_scheduling', '0003_alter_students_overall_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='training_day_arrival',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='training_day_left',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
