# Generated by Django 4.1.3 on 2022-12-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_scheduling', '0005_alter_class_rooms_dates_unavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_rooms',
            name='dates_unavailable',
            field=models.TextField(blank=True, null=True),
        ),
    ]
