# Generated by Django 4.1.3 on 2022-12-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_scheduling', '0006_alter_class_rooms_dates_unavailable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='class_rooms',
            name='dates_unavailable',
        ),
        migrations.AddField(
            model_name='class_rooms',
            name='dates_unavailable',
            field=models.ManyToManyField(blank=True, null=True, related_name='unavailable', to='training_scheduling.date'),
        ),
    ]
