# Generated by Django 4.1.3 on 2023-01-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_scheduling', '0007_date_remove_class_rooms_dates_unavailable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainings',
            name='post_training_comment',
            field=models.CharField(blank=True, default=None, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='trainings',
            name='pre_training_comment',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
